<?php

use Illuminate\Database\Seeder;

class WeaponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('weapons')->insert([
        //シューター
       [ 'name' => 'ボールドマーカー',
         'sub' => 'カーリングボム',
         'special'=>'ウルトラハンコ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'わかばシューター',
         'sub' => 'スプラッシュボム',
         'special'=>'グレートバリア',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'シャープマーカー',
         'sub' => 'クイックボム',
         'special'=>'カニタンク',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'プロモデラー',
         'sub' => 'タンサンボム',
         'special'=>'サメライド',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スプラシューター',
         'sub' => 'キューバンボム',
         'special'=>'ウルトラショット',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => '.52ガロン',
         'sub' => 'スプラッシュシールド',
         'special'=>'メガホンレーザー5.1ch',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'N-ZAP85',
         'sub' => 'キューバンボム',
         'special'=>'エナジースタンド',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'プライムシューター',
         'sub' => 'ラインマーカー',
         'special'=>'カニタンク',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => '.96ガロン',
         'sub' => 'スプリンクラー',
         'special'=>'キューインキ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ジェットスイーパー',
         'sub' => 'ラインマーカー',
         'special'=>'キューインキ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'L3リールガン',
         'sub' => 'カーリングボム',
         'special'=>'カニタンク',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'H3リールガン',
         'sub' => 'ポイントセンサー',
         'special'=>'エナジースタンド',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ボトルカイザー',
         'sub' => 'スプラッシュシールド',
         'special'=>'ウルトラショット',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //ローラー
        ['name' => 'カーボンローラー',
         'sub' => 'ロボットボム',
         'special'=>'ショクワンダー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スプラローラー',
         'sub' => 'カーリングボム',
         'special'=>'グレートバリア',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ダイナモローラー',
         'sub' => 'スプリンクラー',
         'special'=>'エナジースタンド',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ヴァリアブルローラー',
         'sub' => 'トラップ',
         'special'=>'マルチミサイル',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //チャージャー
        ['name' => 'スクイックリンα',
         'sub' => 'ポイントセンサー',
         'special'=>'グレートバリア',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スプラチャージャー',
         'sub' => 'スプラッシュボム',
         'special'=>'キューインキ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スプラスコープ',
         'sub' => 'スプラッシュボム',
         'special'=>'キューインキ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'リッター4K',
         'sub' => 'トラップ',
         'special'=>'ホップソナー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => '4Kスコープ',
         'sub' => 'トラップ',
         'special'=>'ホップソナー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => '14式竹筒銃・甲',
         'sub' => 'ロボットボム',
         'special'=>'メガホンレーザー5.1ch',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ソイチューバー',
         'sub' => 'トーピード',
         'special'=>'マルチミサイル',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //バケツ
        ['name' => 'バケットスロッシャー',
         'sub' => 'スプラッシュボム',
         'special'=>'トリプルトルネード',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ヒッセン',
         'sub' => 'ポイズンミスト',
         'special'=>'ジェットパック',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スクリュースロッシャー',
         'sub' => 'タンサンボム',
         'special'=>'ナイスダマ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'オーバーフロッシャー',
         'sub' => 'スプリンクラー',
         'special'=>'アメフラシ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'エクスプロッシャー',
         'sub' => 'ポイントセンサー',
         'special'=>'アメフラシ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スプラスピナー',
         'sub' => 'クイックボム',
         'special'=>'ウルトラハンコ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'バレルスピナー',
         'sub' => 'スプリンクラー',
         'special'=>'ホップソナー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ハイドラント',
         'sub' => 'ロボットボム',
         'special'=>'ナイスダマ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'クーゲルシュライバー',
         'sub' => 'タンサンボム',
         'special'=>'ジェットパック',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ノーチラス47',
         'sub' => 'ポイントセンサー',
         'special'=>'アメフラシ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //マニューバー
        ['name' => 'スパッタリー',
         'sub' => 'ジャンプビーコン',
         'special'=>'エナジースタンド',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スプラマニューバー',
         'sub' => 'キューバンボム',
         'special'=>'カニタンク',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ケルビン525',
         'sub' => 'スプラッシュシールド',
         'special'=>'ナイスダマ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'デュアルマニューバー',
         'sub' => 'スプラッシュボム',
         'special'=>'ホップソナー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'クアッドホッパーブラック',
         'sub' => 'ロボットボム',
         'special'=>'サメライド',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //パラシェルター
        ['name' => 'キャンピングシェルター',
         'sub' => 'ジャンプビーコン',
         'special'=>'キューインキ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'パラシェルター',
         'sub' => 'スプリンクラー',
         'special'=>'トリプルトルネード',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'スパイガジェット',
         'sub' => 'トラップ',
         'special'=>'サメライド',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //ブラスター
        ['name' => 'ノヴァブラスター',
         'sub' => 'スプラッシュボム',
         'special'=>'ショクワンダー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ホットブラスター',
         'sub' => 'ロボットボム',
         'special'=>'グレートバリア',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ロングブラスター',
         'sub' => 'キューバンボム',
         'special'=>'ホップソナー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'クラッシュブラスター',
         'sub' => 'スプラッシュボム',
         'special'=>'ウルトラショット',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ラピッドブラスター',
         'sub' => 'トラップ',
         'special'=>'トリプルトルネード',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'Rブラスターエリート',
         'sub' => 'ポイズンミスト',
         'special'=>'キューインキ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //筆
        ['name' => 'パブロ',
         'sub' => 'スプラッシュボム',
         'special'=>'メガホンレーザー5.1ch',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ホクサイ',
         'sub' => 'キューバンボム',
         'special'=>'ショクワンダー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //弓
        ['name' => 'トライストリンガー',
         'sub' => 'ポイズンミスト',
         'special'=>'メガホンレーザー5.1ch',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'LACT-450',
         'sub' => 'カーリングボム',
         'special'=>'マルチミサイル',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        //ワイパー
        ['name' => 'ジムワイパー',
         'sub' => 'クイックボム',
         'special'=>'ショクワンダー',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
        ['name' => 'ドライブワイパー',
         'sub' => 'トーピード',
         'special'=>'ウルトラハンコ',
        'created_at' => new DateTime(),
        'updated_at' => new DateTime(),
        ],
       
    ]);
    }
}
